application: ntuproj
version: 6 
runtime: python
api_version: 1

handlers:

- url: /main
  script: ./controls/main.py
  login: required

- url: /coder/.*
  script: ./controls/coder.py
  login: required

- url: /other/.*
  script: ./controls/other.py
  login: required

- url: /chat/.*
  script: ./controls/chat.py
  login: required

- url: /scripts/
  static_dir: scripts

- url: /stylesheets/
  static_dir: stylesheets

- url: /admin/.*
  script: ./controls/admin.py
  login: admin
